"use client";
import { useLocalStore } from "@/utils/store/store";
import "./globals.css";
import { Header } from "@/components/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = useLocalStore((state) => state.theme);
  console.log(theme);

  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
